### ISSUE TITLE
Prepare release 0.6.4: Fix issues with local Bitcoin node 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/dao#38]
See: https://github.com/bisq-network/exchange/issues/1193#issuecomment-359128103 
https://github.com/bisq-network/exchange/issues/1154

**Comment by ManfredKarrer** [comment]
We previously only checked if the P2P network is ready but we now add a check if the node has sufficient BTC peers and it the block download has been completed. The block download completion should cover the case where a localhost btc node is not fully synced (has to be tested if it behaves like that).

We add a check for that case in all tx broadcast use-case like:
- Create offer
- Take offer (taker publishes deposit tx, so we do not need to check on makers side)
- Create payout tx
- Create disputed payout tx 
- Withdraw (end of trade + normal withdrawal)
- Emergency wallet tool
- Manual payout tool for arbitrator

In the UI cases we show popups indicating the reason why the users has to wait.
In the dispute message handling we use a local cache for the messages and event listeners on the relevant data to trigger the check and apply the cached messages. We apply here the btc related checks as well even the message is not requiring that. Only the DisputeResultMessage would require the btc related check. We prefer less code complexity instead of slight optimization here, but it could be optimized in future.

**Comment by cbeams** [comment]
Issue moved to [bisq-network/exchange #1244](https://github.com/bisq-network/exchange/issues/1244) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cbeams** [comment]
Not sure why this issue got created in the bisq-network/dao repository (perhaps because you clicked "New Issue" directly from the bisq-network/dao ZenHub board, @ManfredKarrer? If so, keep in mind that you need to select from the drop-down there the specific repository you want to create a new issue in.)

In any case, I've moved this to bisq-network/exchange#1244 as that's where the work / commits are going to happen.
